name: WilsonStrategic
favicon: null
layout_spectrum: 0.33821
typography_spectrum: 0.51684
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d4232b'
    - '#5a5c5d'
    - '#ffffff'
    - '#5d85a8'
    - '#d3c44f'
  brandStrength: 0.6875
  lightness: 0.8125
  saturation: 0.9041931976098567
  rhythmicContrast: 0.75
purpose: []
